[package]
name = "rustasm6502"
version = "0.1.0"
authors = ["Jonas Schievink <jonas@schievink.net>"]
description = "A 6502 assembler in macro_rules!"
license = "Apache-2.0/MIT"

[dependencies]
#insanity = "*"
